        0x0000,     // Black
        0x000a,     // Blue
        0x00a0,     // Green
        0x00aa,     // Cyan
        0x0a00,     // Red
        0x0a0a,     // Magenta 
        0x0aa0,     // Yellow
        0x0aaa,     // Light Grey
        0x0555,     // Dark Grey
        0x055f,     // Light Blue
        0x05f5,     // Light Green
        0x05ff,     // Light Cyan
        0x0f55,     // Light Red
        0x0f5f,     // Light Magenta
        0x0ff5,     // Light Yellow
        0x0fff,     // White
